# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b958161fa396b55014ea8136d3848c79f71d23cb063554658bdae3481b940c97d9e6208c89b97beccc685f3de406853248663e79417699f153a134af43bf3b1f

test:
  secret_key_base: cf87c8338a1021daf144d0e57c7453675ec68c53d5226147cfc89681c5d6d2484e1a1bf45a080aae99c832fc627066c3b007848802d475fa78b6fc5583cbcea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
